train:
  epochs: 1
  is_conditional: True

lora:
  enable: False
  rank: 16
  alpha: 16
  dropout: 0.0
  target_modules:
    - "q"
    - "k"
    - "v"
    - "o"

scheduler:
  type: "euler"

sampler:
  guide_scale: 1.0